version: '3.8'

services:
  bank-processor:
    image: innovaassolutions/bank-processor:latest
    build: .
    ports:
      - "3005:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./data:/app/data
      - ./merchant_config.txt:/app/merchant_config.txt
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
